### ISSUE TITLE
Your Views form spam

### ISSUE THREAD

**Issue by grange85** [nationalarchives/tna-forms#27]
The Your Views form allowed through thousands of spam email that weren't caught by the "honeypot" - if we could look into this - let me know what you need to try and figure out how this happened?

**Comment by piriyapordes** [comment]
Does this mean we need to rethink having individual email addresses on the site also?

**Comment by mcieslak** [comment]
Do we have many individual email addresses on our site? If so they should definitely be encrypted to avoid spam but as a general approach we should route all queries to our contact forms. Only certain exceptions should be routed directly to an email address...the 'Education service general enquiries' is one example. 

I think in the case of this spam attack it seems the robot has somehow captured the required fields for the form and is bypassing the actual page & automatically submitting - which is probably why the honeypot is not working. Chris may have a different theory!

We definitely need to find out if any other forms/inboxes are being hit with Spam...and implement a more rigorous solution.

**Comment by domingobishop** [comment]
I think that's a fair assessment. The previous attack was hitting the form quite frequently. At times the honeypot caught it and some got through. There are spam bots expecting to find honeypots, so the bots hit with different combinations to beat it.

**Comment by grange85** [comment]
I checked with Abbi and there hasn't been a similar spam attack so I'm closing this on the grounds that it was fixed. We can raise another issue if the problem arises again.
